version: "3.0"

services:
  portfolio-backend:
    image: "portfolio-prod:0.1"
    network_mode: "host"
    build:
      context: ./django/
      dockerfile: Dockerfile-prod
    expose:
      - 8649
    restart: always
    container_name: portfolio-backend
    volumes:
      - /var/www/poojan_projects/portfolio/portfolio-backend/media:/app/media
      - /var/www/poojan_projects/portfolio/portfolio-backend/static:/app/static

  portfolio-frontend:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    ports:
      - "8648:8648"
    restart: always
    stdin_open: true
    container_name: portfolio-frontend
    depends_on:
      - portfolio-backend
