# Generated by Django 4.1.3 on 2022-11-03 16:56

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.datetimemodel')),
                ('title', models.CharField(help_text='Title of the skill', max_length=80)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Skill Progress, can be from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, help_text='Skills Image', upload_to='images')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
            bases=('page.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.datetimemodel')),
                ('title', models.CharField(help_text='Social media Title shown in the page', max_length=50)),
                ('url', models.URLField(help_text='URL for the social media images')),
            ],
            bases=('page.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.datetimemodel')),
                ('title', models.CharField(help_text='Project Title can have upto 255 characters', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Image of the project shown in case study', upload_to='images')),
                ('summary', models.TextField(help_text='Project Summary')),
                ('build_url', models.URLField(blank=True, help_text='Github/Live demo url of the project', max_length=255)),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_tech', to='page.skills')),
            ],
            bases=('page.datetimemodel',),
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.datetimemodel')),
                ('name', models.CharField(help_text='Name should be of max 100 characters, includes first and last name', max_length=100, unique=True)),
                ('role', models.CharField(help_text='Job role of the user', max_length=30)),
                ('image', models.ImageField(blank=True, help_text='Header Image of the user', upload_to='images')),
                ('background_info', models.TextField(help_text='Background information of the user')),
                ('phone_no', models.CharField(help_text='Phone number of the user, should be max 15 characters', max_length=15, unique=True)),
                ('email', models.EmailField(help_text='Email of the user, can be of max 50 characters', max_length=50, unique=True)),
                ('address', models.CharField(blank=True, help_text='Address of the user', max_length=255)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_socials', to='page.socials')),
            ],
            options={
                'verbose_name': 'PageInfo',
                'verbose_name_plural': 'PageInfos',
            },
            bases=('page.datetimemodel',),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.datetimemodel')),
                ('job_title', models.CharField(help_text='Title of the job experienced, has max length of 100 characters', max_length=100)),
                ('company_image', models.ImageField(blank=True, help_text="Company's Image of the respective job", upload_to='images')),
                ('company_info', models.TextField(help_text='Text information of the company')),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('is_working', models.BooleanField(default=False)),
                ('points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='page.skills')),
            ],
            bases=('page.datetimemodel',),
        ),
    ]
