# Generated by Django 4.1.3 on 2022-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinfo',
            name='social',
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='social',
            field=models.ManyToManyField(related_name='social_socials', to='page.socials'),
        ),
    ]
