# Generated by Django 3.2 on 2022-11-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_project_technologies_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Profile picture of the user', upload_to='images'),
        ),
    ]
