kind: Service
apiVersion: v1
metadata:
  name: kubernetes-frontend-service
spec:
  selector:
    app: frontend-container
  ports:
    - nodePort: 3000
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
