# Use the official Python 3.8 image based on slim-bullseye as the base image
FROM python:3.8.12-slim-bullseye

# Set an environment variable to run Python in unbuffered mode
ENV PYTHONUNBUFFERED=1

# Install required dependencies using apt-get package manager
RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    build-essential -y git

# Set the working directory to /app and create it
ENV HOME=/app
ENV APP_HOME=/app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Copy the requirements file to the container
COPY requirements.txt .

# Upgrade pip and install the required packages using pip3
RUN python -m pip install --upgrade pip
RUN pip3 install -r requirements.txt --no-cache-dir

# Copy the entire project to the container's /app directory
COPY . $APP_HOME

# Run tests for the project
RUN python manage.py test

# Set the default command to run the Gunicorn server when the container starts
CMD ["gunicorn", "backend.asgi:application", "--bind", "0.0.0.0:8483", "--worker-class", "uvicorn.workers.UvicornWorker"]
